x-app: &default-app
  build:
    target: base
  image: codepraise-app-python:base
  volumes:
    - ./config/secrets:/app/config/secrets
  environment:
    API_HOST: http://host.docker.internal:8000
    SESSION_SECRET:
  extra_hosts:
    # To resolve "host.docker.internal" when using Linux machines
    # ref: https://medium.com/@TimvanBaarsen/how-to-connect-to-the-docker-host-from-inside-a-docker-container-112b4c71bc66
    - "host.docker.internal:host-gateway"

services:
  app:
    <<: *default-app
    ports:
      - ${PORT:-3000}:3000

  console:
    <<: *default-app
    profiles:
      - debug

  bash:
    <<: *default-app
    tty: true
    profiles:
      - debug
    command: bash
