services:
  # `docker compose -f docker-compose.yml -f docker-compose.prod.yml up`
  app:
    command: inv api.run.prod

  # `docker compose -f docker-compose.yml -f docker-compose.prod.yml run --rm console`
  console:
    command: inv console -e production
