site_name: CodePraise Python
repo_name: codepraise-app-python
repo_url: https://github.com/as10896/codepraise-app-python
edit_uri: edit/main/docs/
theme:
  name: material
  palette:
    primary: indigo
  features:
    - search.suggest
    - search.highlight
markdown_extensions:
  - toc:
      permalink: true
nav:
  - Introduction: index.md
  - architecture.md
  - prerequisite.md
  - docker.md
  - invoke.md
